# Generated by Django 2.0.6 on 2020-12-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StacklottoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmodel',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='faqgroupmodel',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='faqmodel',
            name='question',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='batch',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='reference_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='reference_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
