# Generated by Django 2.0.6 on 2020-12-08 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StacklottoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqGroupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaqModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=140)),
                ('answer', models.TextField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='StacklottoApp.FaqGroupModel')),
            ],
        ),
    ]
