# Generated by Django 2.0.6 on 2020-12-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StacklottoApp', '0002_auto_20201218_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='reference_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
