# Generated by Django 2.0.6 on 2020-12-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StacklottoApp', '0002_faqgroupmodel_faqmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetterSubscriptionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=75, unique=True)),
            ],
        ),
    ]
