# Generated by Django 2.0.6 on 2029-02-11 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StacklottoApp', '0004_contactmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='LotteryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('L649', 'Stacklotto 649'), ('L425', 'Stacklotto 425'), ('LUC5', 'Lucky 5'), ('MAT4', 'Match 4'), ('MAT3', 'Match 3'), ('MAT2', 'Match 2')], max_length=4)),
                ('type', models.CharField(choices=[('EO', 'Exact Order'), ('AO', 'Any Order'), ('XO', 'Exact Order / Any Order'), ('2F', '2 Front Number Play'), ('2B', '2 Back Number Play')], max_length=2)),
                ('prize', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('agent_commission', models.IntegerField(default=20)),
                ('closing_date', models.DateTimeField()),
                ('winning_picks', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=11)),
                ('picks', models.CharField(max_length=50)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StacklottoApp.BatchModel')),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StacklottoApp.LotteryModel')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('F', 'Fund'), ('B', 'Buy Ticket'), ('W', 'Withdrawal')], max_length=1)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Completed')], max_length=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_number', models.CharField(max_length=500)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StacklottoApp.BatchModel')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.AlterModelOptions(
            name='newslettersubscriptionmodel',
            options={'verbose_name': 'Newsletter Email', 'verbose_name_plural': 'Newsletter Emails'},
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='agent_city',
            new_name='agent_location',
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
