# Generated by Django 2.0.6 on 2029-02-11 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StacklottoApp', '0007_auto_20290211_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinnerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='batchmodel',
            options={'verbose_name': 'Batch', 'verbose_name_plural': 'Batches'},
        ),
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'verbose_name': 'Contact Us Message', 'verbose_name_plural': 'Contact Us Messages'},
        ),
        migrations.AlterModelOptions(
            name='faqgroupmodel',
            options={'verbose_name': 'FAQ Group', 'verbose_name_plural': 'FAQ Groups'},
        ),
        migrations.AlterModelOptions(
            name='faqmodel',
            options={'verbose_name': 'Frequently Asked Question', 'verbose_name_plural': 'Frequently Asked Questions'},
        ),
        migrations.AlterModelOptions(
            name='lotterymodel',
            options={'verbose_name': 'Loterry', 'verbose_name_plural': 'Loterries'},
        ),
        migrations.AddField(
            model_name='winnermodel',
            name='lottery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StacklottoApp.LotteryModel'),
        ),
        migrations.AddField(
            model_name='winnermodel',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StacklottoApp.TicketModel'),
        ),
        migrations.AddField(
            model_name='winnermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
