# Generated by Django 2.0.6 on 2029-02-11 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StacklottoApp', '0008_auto_20290211_0154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='winnermodel',
            options={'verbose_name': 'Winner', 'verbose_name_plural': 'Winners'},
        ),
    ]
