# Generated by Django 2.0.6 on 2030-04-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StacklottoApp', '0009_auto_20290211_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
