# Generated by Django 2.0.6 on 2030-04-11 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('StacklottoApp', '0010_auto_20300411_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionmodel',
            name='batch',
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='details',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='type',
            field=models.CharField(choices=[('F', 'Wallet Fund'), ('B', 'Buy Ticket'), ('W', 'Withdrawal')], max_length=1),
        ),
    ]
