# Generated by Django 2.0.6 on 2037-08-12 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StacklottoApp', '0011_auto_20300411_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Affiliate',
                'verbose_name_plural': 'Affiliates',
            },
        ),
        migrations.CreateModel(
            name='AgentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_status', models.CharField(choices=[('ANA', 'Not Applied'), (('AA',), 'Applied'), ('AC', 'Confirmed')], default='ANA', max_length=3)),
                ('agent_code', models.CharField(blank=True, max_length=50, null=True)),
                ('agent_location', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='type',
            field=models.CharField(choices=[('F', 'Wallet Funded'), ('B', 'Buy Ticket'), ('W', 'Withdrawal')], max_length=1),
        ),
    ]
