# Generated by Django 2.0.6 on 2037-08-12 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StacklottoApp', '0012_auto_20370812_0139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentmodel',
            options={'verbose_name': 'Agent', 'verbose_name_plural': 'Agents'},
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='agent_code',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='agent_location',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='agent_status',
        ),
    ]
