# Generated by Django 2.0.6 on 2037-08-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StacklottoApp', '0014_auto_20370812_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotterymodel',
            name='type',
        ),
        migrations.AddField(
            model_name='ticketmodel',
            name='type',
            field=models.CharField(choices=[('EO', 'Exact Order'), ('AO', 'Any Order'), ('XO', 'Exact Order / Any Order'), ('2F', '2 Front Number Play'), ('2B', '2 Back Number Play')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lotterymodel',
            name='name',
            field=models.CharField(choices=[('L649', 'Stacklotto 649'), ('L425', 'Stacklotto 425'), ('LUC5', 'Lucky 5'), ('MAT4', 'Match 4'), ('MAT3', 'Match 3'), ('MAT2', 'Match 2')], max_length=4, unique=True),
        ),
    ]
