# Generated by Django 2.0.6 on 2037-08-12 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StacklottoApp', '0015_auto_20370812_0630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lotterymodel',
            old_name='closing_date',
            new_name='draw_date',
        ),
    ]
