# Generated by Django 2.0.6 on 2037-08-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StacklottoApp', '0016_auto_20370812_0706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionmodel',
            options={'ordering': ['-date'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='reference_number',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
