# Generated by Django 2.0.6 on 2020-12-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StacklottoApp', '0017_auto_20370812_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchmodel',
            name='reference_number',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='reference_number',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='type',
            field=models.CharField(blank=True, choices=[('EO', 'Exact Order'), ('AO', 'Any Order'), ('XO', 'Exact Order / Any Order'), ('2F', '2 Front Number Play'), ('2B', '2 Back Number Play')], max_length=2, null=True),
        ),
    ]
