# Generated by Django 2.0.6 on 2020-12-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StacklottoApp', '0018_auto_20201217_0330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='ticketmodel',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketmodel',
            name='phone',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='batch',
            field=models.CharField(max_length=500),
        ),
        migrations.DeleteModel(
            name='BatchModel',
        ),
    ]
