# Generated by Django 2.0.6 on 2020-12-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StacklottoApp', '0019_auto_20201217_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotterymodel',
            name='name',
            field=models.CharField(choices=[('L649', 'Stacklotto 649'), ('L425', 'Stacklotto 425'), ('LUC5', 'Lucky 5'), ('MAT4', 'Match 4'), ('MAT3', 'Match 3'), ('MAT2', 'Match 2')], max_length=4),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='batch',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='reference_number',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='reference_number',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
